-- MySQL Script generated by MySQL Workbench
-- sáb 12 nov 2022 08:22:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `anexos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anexos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `anexos` (
  `idAnexos` INT NOT NULL AUTO_INCREMENT,
  `anexo` VARCHAR(45) NULL DEFAULT NULL,
  `thumb` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(300) NULL DEFAULT NULL,
  `path` VARCHAR(300) NULL DEFAULT NULL,
  `os_id` INT(11) NOT NULL,
  PRIMARY KEY (`idAnexos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `anotacoes_os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anotacoes_os` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `anotacoes_os` (
  `idAnotacoes` INT(11) NOT NULL AUTO_INCREMENT,
  `anotacao` VARCHAR(255) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `os_id` INT(11) NOT NULL,
  PRIMARY KEY (`idAnotacoes`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(80) NULL DEFAULT NULL,
  `cadastro` DATE NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `tipo` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ci_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ci_sessions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `id` VARCHAR(128) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `data` BLOB NOT NULL);

SHOW WARNINGS;
CREATE INDEX `ci_sessions_timestamp` ON `ci_sessions` (`timestamp` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `clientes` (
  `idClientes` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(255) NOT NULL,
  `sexo` VARCHAR(20) NULL DEFAULT NULL,
  `pessoa_fisica` TINYINT NOT NULL DEFAULT 1,
  `documento` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `celular` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `dataCadastro` DATE NULL DEFAULT NULL,
  `rua` VARCHAR(70) NULL DEFAULT NULL,
  `numero` VARCHAR(15) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(20) NULL DEFAULT NULL,
  `cep` VARCHAR(20) NULL DEFAULT NULL,
  `contato` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `fornecedor` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cobrancas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cobrancas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cobrancas` (
  `idCobranca` INT(11) NOT NULL AUTO_INCREMENT,
  `charge_id` VARCHAR(255) NULL DEFAULT NULL,
  `conditional_discount_date` DATE NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `custom_id` INT(11) NULL DEFAULT NULL,
  `expire_at` DATE NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `payment_method` VARCHAR(11) NULL DEFAULT NULL,
  `payment_url` VARCHAR(255) NULL DEFAULT NULL,
  `request_delivery_address` VARCHAR(64) NULL DEFAULT NULL,
  `status` VARCHAR(36) NOT NULL,
  `total` VARCHAR(15) NULL DEFAULT NULL,
  `barcode` VARCHAR(255) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `payment_gateway` VARCHAR(255) NULL DEFAULT NULL,
  `payment` VARCHAR(64) NOT NULL,
  `pdf` VARCHAR(255) NULL DEFAULT NULL,
  `vendas_id` INT(11) NULL DEFAULT NULL,
  `os_id` INT(11) NULL DEFAULT NULL,
  `clientes_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idCobranca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `configuracoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `configuracoes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `configuracoes` (
  `idConfig` INT NOT NULL AUTO_INCREMENT,
  `config` VARCHAR(20) NOT NULL,
  `valor` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idConfig`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX ON `configuracoes` (`config` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `contas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `contas` (
  `idContas` INT NOT NULL AUTO_INCREMENT,
  `conta` VARCHAR(45) NULL DEFAULT NULL,
  `banco` VARCHAR(45) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `saldo` DECIMAL(10,2) NULL DEFAULT NULL,
  `cadastro` DATE NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `tipo` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`idContas`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `documentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `documentos` (
  `idDocumentos` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(70) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `file` VARCHAR(100) NULL DEFAULT NULL,
  `path` VARCHAR(300) NULL DEFAULT NULL,
  `url` VARCHAR(300) NULL DEFAULT NULL,
  `cadastro` DATE NULL DEFAULT NULL,
  `categoria` VARCHAR(80) NULL DEFAULT NULL,
  `tipo` VARCHAR(15) NULL DEFAULT NULL,
  `tamanho` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDocumentos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `email_queue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `email_queue` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `email_queue` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `to` VARCHAR(255) NOT NULL,
  `cc` VARCHAR(255) NULL DEFAULT NULL,
  `bcc` VARCHAR(255) NULL DEFAULT NULL,
  `message` TEXT NOT NULL,
  `status` ENUM('pending', 'sending', 'sent', 'failed') NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `headers` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `emitente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emitente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `emitente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `cnpj` VARCHAR(45) NULL DEFAULT NULL,
  `ie` VARCHAR(50) NULL DEFAULT NULL,
  `rua` VARCHAR(70) NULL DEFAULT NULL,
  `numero` VARCHAR(15) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(20) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `url_logo` VARCHAR(225) NULL DEFAULT NULL,
  `cep` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `equipamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `equipamentos` (
  `idEquipamentos` INT NOT NULL AUTO_INCREMENT,
  `equipamento` VARCHAR(150) NOT NULL,
  `num_serie` VARCHAR(80) NULL DEFAULT NULL,
  `modelo` VARCHAR(80) NULL DEFAULT NULL,
  `cor` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(150) NULL DEFAULT NULL,
  `tensao` VARCHAR(45) NULL DEFAULT NULL,
  `potencia` VARCHAR(45) NULL DEFAULT NULL,
  `voltagem` VARCHAR(45) NULL DEFAULT NULL,
  `data_fabricacao` DATE NULL DEFAULT NULL,
  `marcas_id` INT NULL DEFAULT NULL,
  `clientes_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idEquipamentos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `equipamentos_os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equipamentos_os` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `equipamentos_os` (
  `idEquipamentos_os` INT NOT NULL AUTO_INCREMENT,
  `defeito_declarado` VARCHAR(200) NULL DEFAULT NULL,
  `defeito_encontrado` VARCHAR(200) NULL DEFAULT NULL,
  `solucao` VARCHAR(45) NULL DEFAULT NULL,
  `equipamentos_id` INT NULL DEFAULT NULL,
  `os_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idEquipamentos_os`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `garantias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garantias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `garantias` (
  `idGarantias` INT NOT NULL AUTO_INCREMENT,
  `dataGarantia` DATE NULL DEFAULT NULL,
  `refGarantia` VARCHAR(15) NULL DEFAULT NULL,
  `textoGarantia` TEXT NULL DEFAULT NULL,
  `usuarios_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idGarantias`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `itens_de_vendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itens_de_vendas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `itens_de_vendas` (
  `idItens` INT NOT NULL AUTO_INCREMENT,
  `subTotal` DECIMAL(10,2) NULL DEFAULT 0,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT 0,
  `vendas_id` INT NOT NULL,
  `produtos_id` INT(11) NOT NULL,
  PRIMARY KEY (`idItens`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lancamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lancamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lancamentos` (
  `idLancamentos` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT 0,
  `desconto` DECIMAL(10,2) NULL DEFAULT 0,
  `valor_desconto` DECIMAL(10,2) NULL DEFAULT 0,
  `data_vencimento` DATE NOT NULL,
  `data_pagamento` DATE NULL DEFAULT NULL,
  `baixado` TINYINT(1) NULL DEFAULT 0,
  `cliente_fornecedor` VARCHAR(255) NULL DEFAULT NULL,
  `forma_pgto` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `anexo` VARCHAR(250) NULL DEFAULT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `clientes_id` INT(11) NULL DEFAULT NULL,
  `categorias_id` INT NULL DEFAULT NULL,
  `contas_id` INT NULL DEFAULT NULL,
  `vendas_id` INT NULL DEFAULT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`idLancamentos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `logs` (
  `idLogs` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(80) NULL DEFAULT NULL,
  `tarefa` VARCHAR(100) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idLogs`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marcas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `marcas` (
  `idMarcas` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(100) NULL DEFAULT NULL,
  `cadastro` DATE NULL DEFAULT NULL,
  `situacao` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idMarcas`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `migrations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `migrations` (
  `version` BIGINT(20) NOT NULL);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `os` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `os` (
  `idOs` INT(11) NOT NULL AUTO_INCREMENT,
  `dataInicial` DATE NULL DEFAULT NULL,
  `dataFinal` DATE NULL DEFAULT NULL,
  `garantia` VARCHAR(45) NULL DEFAULT NULL,
  `descricaoProduto` TEXT NULL DEFAULT NULL,
  `defeito` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `laudoTecnico` TEXT NULL DEFAULT NULL,
  `valorTotal` DECIMAL(10,2) NULL DEFAULT 0,
  `desconto` DECIMAL(10,2) NULL DEFAULT 0,
  `valor_desconto` DECIMAL(10,2) NULL DEFAULT 0,
  `clientes_id` INT(11) NOT NULL,
  `usuarios_id` INT(11) NOT NULL,
  `lancamento` INT(11) NULL DEFAULT NULL,
  `faturado` TINYINT(1) NOT NULL,
  `garantias_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idOs`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_os_garantias1` ON `os` (`garantias_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `permissoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permissoes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `permissoes` (
  `idPermissao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `permissoes` TEXT NULL DEFAULT NULL,
  `situacao` TINYINT(1) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idPermissao`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `produtos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `produtos` (
  `idProdutos` INT(11) NOT NULL AUTO_INCREMENT,
  `codDeBarra` VARCHAR(70) NOT NULL,
  `descricao` VARCHAR(80) NOT NULL,
  `unidade` VARCHAR(10) NULL DEFAULT NULL,
  `precoCompra` DECIMAL(10,2) NULL DEFAULT NULL,
  `precoVenda` DECIMAL(10,2) NOT NULL,
  `estoque` INT(11) NOT NULL,
  `estoqueMinimo` INT(11) NULL DEFAULT NULL,
  `saida` TINYINT(1) NULL DEFAULT NULL,
  `entrada` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `produtos_os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `produtos_os` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `produtos_os` (
  `idProdutos_os` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(11) NOT NULL,
  `descricao` VARCHAR(80) NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT 0,
  `os_id` INT(11) NOT NULL,
  `produtos_id` INT(11) NOT NULL,
  `subTotal` DECIMAL(10,2) NULL DEFAULT 0,
  PRIMARY KEY (`idProdutos_os`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `resets_de_senha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resets_de_senha` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `resets_de_senha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `data_expiracao` DATETIME NOT NULL,
  `token_utilizado` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `servicos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `servicos` (
  `idServicos` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idServicos`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `servicos_os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `servicos_os` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `servicos_os` (
  `idServicos_os` INT(11) NOT NULL AUTO_INCREMENT,
  `servico` VARCHAR(80) NULL DEFAULT NULL,
  `quantidade` DOUBLE NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT 0,
  `os_id` INT(11) NOT NULL,
  `servicos_id` INT(11) NOT NULL,
  `subTotal` DECIMAL(10,2) NULL DEFAULT 0,
  PRIMARY KEY (`idServicos_os`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `idUsuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `rg` VARCHAR(20) NULL DEFAULT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `rua` VARCHAR(70) NULL DEFAULT NULL,
  `numero` VARCHAR(15) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `celular` VARCHAR(20) NULL DEFAULT NULL,
  `situacao` TINYINT(1) NOT NULL,
  `dataCadastro` DATE NOT NULL,
  `permissoes_id` INT NOT NULL,
  `dataExpiracao` DATE NULL DEFAULT NULL,
  `asaas_id` VARCHAR(255) NULL DEFAULT NULL,
  `url_image_user` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vendas` (
  `idVendas` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NULL DEFAULT NULL,
  `valorTotal` DECIMAL(10,2) NULL DEFAULT 0,
  `desconto` DECIMAL(10,2) NULL DEFAULT 0,
  `valor_desconto` DECIMAL(10,2) NULL DEFAULT 0,
  `faturado` TINYINT(1) NULL DEFAULT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `observacoes_cliente` TEXT NULL DEFAULT NULL,
  `clientes_id` INT(11) NOT NULL,
  `usuarios_id` INT(11) NULL DEFAULT NULL,
  `lancamentos_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idVendas`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
